//Map Exported with Texture Studio By: [uL]Pottus////////////////////////////////////////////////////////////////
//////////////////////////////////////////////and Crayder////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Map Information////////////////////////////////////////////////////////////////////////////////////////////////
/*
	Exported on "2019-11-24 18:27:41" by "renault"
	Created by "renault"
*/
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//Objects////////////////////////////////////////////////////////////////////////////////////////////////////////
static ___tmpofsfdgfsdfsfa;
___tmpofsfdgfsdfsfa = CreateDynamicObject(19377, 918.957519, -832.374694, 1086.571166, 0.000000, 90.000000, 90.000000, -1, 2, -1, 300.00, 300.00); 
SetDynamicObjectMaterial(___tmpofsfdgfsdfsfa, 0, 16071, "des_quarrybelts", "sjmlawarwall5", 0x00000000);
___tmpofsfdgfsdfsfa = CreateDynamicObject(19377, 928.591491, -832.374694, 1086.571166, 0.000000, 90.000000, 90.000000, -1, 2, -1, 300.00, 300.00); 
SetDynamicObjectMaterial(___tmpofsfdgfsdfsfa, 0, 16071, "des_quarrybelts", "sjmlawarwall5", 0x00000000);
___tmpofsfdgfsdfsfa = CreateDynamicObject(19445, 914.232421, -831.976623, 1088.402954, 0.000000, 0.000000, 0.000000, -1, 2, -1, 300.00, 300.00); 
SetDynamicObjectMaterial(___tmpofsfdgfsdfsfa, 0, 9625, "garage_sfw", "garage1b_sfw", 0x00000000);
___tmpofsfdgfsdfsfa = CreateDynamicObject(19445, 918.960327, -836.881896, 1088.402954, 0.000000, 0.000000, 90.000000, -1, 2, -1, 300.00, 300.00); 
SetDynamicObjectMaterial(___tmpofsfdgfsdfsfa, 0, 9625, "garage_sfw", "garage1b_sfw", 0x00000000);
___tmpofsfdgfsdfsfa = CreateDynamicObject(19445, 928.592285, -836.881896, 1088.402954, 0.000000, 0.000000, 90.000000, -1, 2, -1, 300.00, 300.00); 
SetDynamicObjectMaterial(___tmpofsfdgfsdfsfa, 0, 9625, "garage_sfw", "garage1b_sfw", 0x00000000);
___tmpofsfdgfsdfsfa = CreateDynamicObject(19445, 929.982421, -831.976623, 1088.402954, 0.000000, 0.000000, 0.000000, -1, 2, -1, 300.00, 300.00); 
SetDynamicObjectMaterial(___tmpofsfdgfsdfsfa, 0, 9625, "garage_sfw", "garage1b_sfw", 0x00000000);
___tmpofsfdgfsdfsfa = CreateDynamicObject(19445, 928.592285, -827.206909, 1088.402954, 0.000000, 0.000000, 90.000000, -1, 2, -1, 300.00, 300.00); 
SetDynamicObjectMaterial(___tmpofsfdgfsdfsfa, 0, 9625, "garage_sfw", "garage1b_sfw", 0x00000000);
___tmpofsfdgfsdfsfa = CreateDynamicObject(19445, 918.960327, -827.206909, 1088.402954, 0.000000, 0.000000, 90.000000, -1, 2, -1, 300.00, 300.00); 
SetDynamicObjectMaterial(___tmpofsfdgfsdfsfa, 0, 9625, "garage_sfw", "garage1b_sfw", 0x00000000);
___tmpofsfdgfsdfsfa = CreateDynamicObject(19377, 928.591491, -832.374694, 1090.200927, 0.000000, 90.000000, 90.000000, -1, 2, -1, 300.00, 300.00); 
SetDynamicObjectMaterial(___tmpofsfdgfsdfsfa, 0, 16071, "des_quarrybelts", "sjmlawarwall5", 0x00000000);
___tmpofsfdgfsdfsfa = CreateDynamicObject(19377, 918.957519, -832.374694, 1090.200927, 0.000000, 90.000000, 90.000000, -1, 2, -1, 300.00, 300.00); 
SetDynamicObjectMaterial(___tmpofsfdgfsdfsfa, 0, 16071, "des_quarrybelts", "sjmlawarwall5", 0x00000000);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////
___tmpofsfdgfsdfsfa = CreateDynamicObject(3352, 929.920471, -831.871215, 1087.906372, 0.000000, 0.000000, 0.000000, -1, 2, -1, 300.00, 300.00); 
