// GLOBAL ITEMS ID
new stock
	gItem_Hamburger,
	gItem_Beans,
	gItem_EnergyBar,
	gItem_DriedMeat,
	gItem_PeanutButter,
	gItem_CannedTuna,
	gItem_RawMeat,
	gItem_RawFish,

	gItem_BottleOfWater,
	gItem_SmallBottleOfWater,
	gItem_Milk,
	gItem_RainWater,

	gItem_RationK,
	gItem_Morfine,
	gItem_Bandages,
	gItem_Medikit,

	gItem_SmallBackPack,
	gItem_BigBackPack,

	// AMMOS
	gItem_LightAmmo,
	gItem_BuckShotAmmo,
	gItem_HeavyAmmo,
	gItem_RifleAmmo,

	// Fuel
	gItem_SmallFuelTank,
	gItem_MediumFuelTank,
	gItem_BigFuelTank,

	// Drugs
	gItem_PCP,
	gItem_Xanax,
	gItem_MDMA,
	gItem_Crack,
	gItem_Steroids,
	gItem_Oxycodone,
	gItem_Marijuana,
	gItem_Hashish,
	gItem_Coke,
	gItem_Eroine,
	gItem_Meth,
	gItem_LSD,

	gItem_Bread,
	gItem_BreadPiece,
	gItem_PackedMeat,
	gItem_Cerelas,
	gItem_IceCream,
	gItem_Tomato,
	gItem_RedApple,
	gItem_GreenApple,
	gItem_Orange,
	gItem_Banana,
	gItem_OrangeJuice,
	gItem_AppleJuice,

	gItem_MechanicalComponents,
	gItem_Money,

	gItem_Radio,

	gItem_Cigarette,

	gItem_Dress
;